import type { ActionId } from '../sim/action';

/**
 * One-line player-facing summaries for the Roster sheet's Dice Faces
 * tooltip — the mechanical detail lives on each Action itself (see
 * sim/actions/*.ts), this is just plain-language flavor text.
 */
export const ACTION_DESCRIPTIONS: Partial<Record<ActionId, string>> = {
  'attack-nearest': 'Melee hit on the nearest enemy (front row first).',
  'attack-lowest-hp': 'Melee hit finishing off the weakest reachable enemy.',
  'power-attack': 'Hard-hitting melee strike on the weakest reachable enemy.',
  cleave: 'Melee hit that strikes every enemy in the target\'s row.',
  fear: 'Makes every enemy in the target\'s row take more damage for a few turns.',
  'rallying-strike': 'Melee hit that also grants the whole party temporary armor.',
  'piercing-strike': 'From the front row, can finish off the weakest enemy in either row.',
  'pickpocket-strike': 'Melee hit with a chance to generate bonus gold.',
  'gilded-strike': "Melee hit that deals more damage the more gold the party's carrying.",
  'ranged-shot': 'Ranged hit — can reach either enemy row directly.',
  'blinding-bolt': "Ranged hit that also lowers the target's attack power for a few turns.",
  'card-throw': 'Ranged hit on a random enemy with a wide damage swing.',
  'mourning-strike': 'Ranged hit that deals more damage the more Mending Charge energy is banked.',
  heal: 'Heals the lowest-HP ally.',
  'self-heal': 'Heals self once below half health.',
  'mending-charge': 'Every turn, heals the ally standing in front of her (or the lowest-HP hurt ally) and banks energy.',
  'splash-heal': 'Every turn, heals the lowest-HP hurt ally and splashes half as much onto allies next to them.',
  volley: 'Ranged hit on three random enemies at once, at full damage.',
  'battle-orders': 'Two allies each make a bonus attack right now.',
  'guardians-vow': 'Shields the ally standing in front of her; the shield grows with her banked energy.',
  empower: "Grants the ally currently hitting hardest a temporary attack boost.",
  command: 'Grants a random ally a bonus attack right now.',
  inspire: 'Grants the whole party temporary critical chance.',
  retreat: 'Ends the room early and retreats the party.',
  'sneak-strike': 'Usually a melee hit on the nearest enemy, but can slip past the front row to strike a random enemy in the back instead.',
  'focused-shot': 'Ranged hit on the weakest enemy, in either row — lower damage than a heavy strike.',
  'potion-toss-ally': 'Throws a random buff (attack or critical chance) at a random ally.',
  'potion-toss-enemy': 'Throws a random debuff (attack or vulnerability) at a random enemy.',
  'execute-strike': 'Melee hit that instantly finishes off a target already critically low on HP.',
  'chain-strike': 'Ranged hit that also bounces to a couple of other enemies for reduced damage.',
  'venom-sting': 'Melee hit that poisons the target, dealing damage over time.',
  'lifesteal-strike': 'Melee hit that heals the attacker for a portion of the damage dealt.',
  'scatter-shot': 'Ranged hit that strikes several random enemies at once.',
  cleanse: "Clears every active status effect (Burn, Poison, etc.) from the lowest-HP ally.",
  revive: 'Brings a Downed ally back into the fight at partial HP.',
  'shield-wall': 'Grants the lowest-HP ally a shield that absorbs damage before HP.',
  taunt: 'Forces enemies to target the caster for a few turns.',
  mark: "Marks an enemy, making them take more damage for a few turns.",
  silence: "Suppresses an enemy's Special Action for a few turns (their Basic Action still fires).",
  stun: "Skips an enemy's entire next turn.",
  'guardians-ward': 'Grants the lowest-HP ally full damage immunity for a turn.',
  vanish: 'Makes the caster untargetable for a few turns.',
};
